//! Learning event types and event bus.
//!
//! Defines the [`LearningEvent`] enum capturing observable agent actions,
//! the [`LearningEventBus`] for async publish/subscribe, and the
//! [`LearningAction`] enum representing outcomes of processing events.

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tokio::sync::broadcast;

/// Default channel capacity for the learning event bus.
const LEARNING_BUS_CAPACITY: usize = 256;

/// Classification of tool-call errors.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ErrorClassification {
    /// Problem with user input.
    UserInput,
    /// Problem with tool configuration.
    ToolConfig,
    /// Environmental issue (network, permissions, etc.).
    Environment,
    /// Agent chose the wrong tool or strategy.
    AgentStrategy,
    /// Skill was incomplete or missing steps.
    SkillIncomplete,
}

/// Outcome of a skill invocation.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SkillOutcome {
    /// Skill was helpful.
    Helpful,
    /// Skill was activated but irrelevant.
    Irrelevant,
    /// Skill caused problems.
    Harmful,
}

/// A learning event — something observable that the agent can learn from.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum LearningEvent {
    /// A tool invocation succeeded.
    ToolSucceeded {
        tool: String,
        args_summary: String,
        duration_ms: u64,
        context_hash: String,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// A tool invocation failed.
    ToolFailed {
        tool: String,
        args_summary: String,
        error: ErrorClassification,
        error_message: String,
        retry_count: u32,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// The user corrected the agent's behaviour.
    UserCorrection {
        original_action: String,
        correction_hint: String,
        topic: String,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// The user approved or acknowledged an action.
    UserApproval {
        action_taken: String,
        implicit: bool,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// A skill was used.
    SkillUsed {
        skill_name: String,
        match_score: f64,
        outcome: SkillOutcome,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// A new skill was created.
    SkillCreated {
        skill_name: String,
        trigger_reason: String,
        source_session: String,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// Memory was accessed.
    MemoryAccessed {
        query: String,
        results_count: usize,
        hit: bool,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
    /// A post-task reflection was generated by the LLM.
    TaskReflection {
        /// Brief summary of the completed task.
        task_summary: String,
        /// Number of tool calls made during the task.
        tool_calls_count: u32,
        /// Whether the task completed successfully.
        success: bool,
        /// LLM-generated reflection text (1-2 sentences).
        reflection: String,
        #[serde(with = "chrono::serde::ts_seconds")]
        timestamp: DateTime<Utc>,
        /// Trace ID linking back to the originating user request.
        #[serde(default, skip_serializing_if = "Option::is_none")]
        trace_id: Option<String>,
    },
}

impl LearningEvent {
    /// Returns the timestamp of this event.
    pub fn timestamp(&self) -> DateTime<Utc> {
        match self {
            Self::ToolSucceeded { timestamp, .. }
            | Self::ToolFailed { timestamp, .. }
            | Self::UserCorrection { timestamp, .. }
            | Self::UserApproval { timestamp, .. }
            | Self::SkillUsed { timestamp, .. }
            | Self::SkillCreated { timestamp, .. }
            | Self::MemoryAccessed { timestamp, .. }
            | Self::TaskReflection { timestamp, .. } => *timestamp,
        }
    }

    /// Returns the trace ID linking this event back to the originating user request.
    pub fn trace_id(&self) -> Option<&str> {
        match self {
            Self::ToolSucceeded { trace_id, .. }
            | Self::ToolFailed { trace_id, .. }
            | Self::UserCorrection { trace_id, .. }
            | Self::UserApproval { trace_id, .. }
            | Self::SkillUsed { trace_id, .. }
            | Self::SkillCreated { trace_id, .. }
            | Self::MemoryAccessed { trace_id, .. }
            | Self::TaskReflection { trace_id, .. } => trace_id.as_deref(),
        }
    }
}

/// An action produced by processing a learning event.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum LearningAction {
    /// No action needed.
    NoOp,
    /// Adjust a skill's confidence score.
    AdjustConfidence { skill: String, delta: f64 },
    /// Propose creating a new skill.
    ProposeSkill { name: String, reason: String },
    /// Propose patching an existing skill.
    PatchSkill { skill: String, description: String },
    /// Deprecate a skill.
    DeprecateSkill { skill: String, reason: String },
    /// Record an insight to long-term memory.
    RecordInsight { insight: String, category: String },
}

/// Async event bus for learning events using tokio broadcast.
#[derive(Debug, Clone)]
pub struct LearningEventBus {
    tx: broadcast::Sender<LearningEvent>,
}

impl LearningEventBus {
    /// Creates a new event bus with the default channel capacity.
    pub fn new() -> Self {
        Self::with_capacity(LEARNING_BUS_CAPACITY)
    }

    /// Creates a new event bus with a custom channel capacity.
    pub fn with_capacity(capacity: usize) -> Self {
        let (tx, _) = broadcast::channel(capacity);
        Self { tx }
    }

    /// Publishes a learning event to all subscribers.
    ///
    /// Returns the number of receivers that received the event.
    /// If no receivers exist, the event is silently dropped.
    pub fn publish(&self, event: LearningEvent) -> usize {
        self.tx.send(event).unwrap_or(0)
    }

    /// Subscribes to learning events.
    ///
    /// The returned receiver will see events published after this call.
    /// Events published before subscribing are not replayed.
    pub fn subscribe(&self) -> broadcast::Receiver<LearningEvent> {
        self.tx.subscribe()
    }

    /// Returns a sender handle that can be used to publish events.
    pub fn sender(&self) -> broadcast::Sender<LearningEvent> {
        self.tx.clone()
    }
}

impl Default for LearningEventBus {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn event_bus_publish_subscribe() {
        let bus = LearningEventBus::new();
        let mut rx = bus.subscribe();

        let event = LearningEvent::ToolSucceeded {
            tool: "shell".into(),
            args_summary: "ls -la".into(),
            duration_ms: 150,
            context_hash: "abc123".into(),
            timestamp: Utc::now(),
            trace_id: None,
        };

        bus.publish(event.clone());
        let received = rx.try_recv().expect("should receive event");
        assert!(matches!(received, LearningEvent::ToolSucceeded { .. }));
    }

    #[test]
    fn event_bus_no_subscribers() {
        let bus = LearningEventBus::new();
        let event = LearningEvent::ToolSucceeded {
            tool: "shell".into(),
            args_summary: "echo hi".into(),
            duration_ms: 10,
            context_hash: "def".into(),
            timestamp: Utc::now(),
            trace_id: None,
        };
        // Should not panic when no subscribers
        assert_eq!(bus.publish(event), 0);
    }

    #[test]
    fn event_bus_multiple_subscribers() {
        let bus = LearningEventBus::new();
        let mut rx1 = bus.subscribe();
        let mut rx2 = bus.subscribe();

        let event = LearningEvent::MemoryAccessed {
            query: "test".into(),
            results_count: 3,
            hit: true,
            timestamp: Utc::now(),
            trace_id: None,
        };

        assert_eq!(bus.publish(event), 2);
        assert!(rx1.try_recv().is_ok());
        assert!(rx2.try_recv().is_ok());
    }

    #[test]
    fn event_timestamp() {
        let ts = Utc::now();
        let event = LearningEvent::SkillCreated {
            skill_name: "my-skill".into(),
            trigger_reason: "repeated pattern".into(),
            source_session: "sess-1".into(),
            timestamp: ts,
            trace_id: None,
        };
        assert_eq!(event.timestamp(), ts);
    }

    #[test]
    fn event_trace_id_accessor() {
        let event = LearningEvent::ToolSucceeded {
            tool: "shell".into(),
            args_summary: "ls".into(),
            duration_ms: 50,
            context_hash: "h".into(),
            timestamp: Utc::now(),
            trace_id: Some("trace-abc".into()),
        };
        assert_eq!(event.trace_id(), Some("trace-abc"));

        let event_no_trace = LearningEvent::ToolSucceeded {
            tool: "shell".into(),
            args_summary: "ls".into(),
            duration_ms: 50,
            context_hash: "h".into(),
            timestamp: Utc::now(),
            trace_id: None,
        };
        assert_eq!(event_no_trace.trace_id(), None);
    }

    #[test]
    fn event_serde_roundtrip() {
        let event = LearningEvent::ToolFailed {
            tool: "web_fetch".into(),
            args_summary: "https://example.com".into(),
            error: ErrorClassification::Environment,
            error_message: "connection timeout".into(),
            retry_count: 3,
            timestamp: Utc::now(),
            trace_id: Some("trace-xyz".into()),
        };
        let json = serde_json::to_string(&event).expect("serialize");
        let decoded: LearningEvent = serde_json::from_str(&json).expect("deserialize");
        assert!(matches!(decoded, LearningEvent::ToolFailed { .. }));
        assert_eq!(decoded.trace_id(), Some("trace-xyz"));
    }

    #[test]
    fn event_serde_backward_compat() {
        // Old-format JSON without trace_id should deserialize with trace_id = None.
        let old_json = r#"{"type":"tool_succeeded","tool":"shell","args_summary":"ls","duration_ms":10,"context_hash":"h","timestamp":1700000000}"#;
        let decoded: LearningEvent =
            serde_json::from_str(old_json).expect("deserialize old format");
        assert!(matches!(decoded, LearningEvent::ToolSucceeded { .. }));
        assert_eq!(decoded.trace_id(), None);
    }

    #[test]
    fn event_serde_skips_none_trace_id() {
        let event = LearningEvent::ToolSucceeded {
            tool: "shell".into(),
            args_summary: "ls".into(),
            duration_ms: 10,
            context_hash: "h".into(),
            timestamp: Utc::now(),
            trace_id: None,
        };
        let json = serde_json::to_string(&event).expect("serialize");
        assert!(
            !json.contains("trace_id"),
            "None trace_id should be skipped"
        );
    }

    #[test]
    fn learning_action_serde() {
        let action = LearningAction::AdjustConfidence {
            skill: "my-skill".into(),
            delta: -0.1,
        };
        let json = serde_json::to_string(&action).expect("serialize");
        let decoded: LearningAction = serde_json::from_str(&json).expect("deserialize");
        assert_eq!(action, decoded);
    }

    #[test]
    fn task_reflection_serde_roundtrip() {
        let event = LearningEvent::TaskReflection {
            task_summary: "deploy to prod".into(),
            tool_calls_count: 3,
            success: true,
            reflection: "Good execution but consider caching build artifacts.".into(),
            timestamp: Utc::now(),
            trace_id: Some("trace-refl".into()),
        };
        let json = serde_json::to_string(&event).expect("serialize");
        let decoded: LearningEvent = serde_json::from_str(&json).expect("deserialize");
        assert!(matches!(decoded, LearningEvent::TaskReflection { .. }));
        assert_eq!(decoded.trace_id(), Some("trace-refl"));
    }
}
